package com.employeeinfo.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.employeeinfo.controller.EmployeeForm;
import com.employeeinfo.dao.AddressRepository;
import com.employeeinfo.dao.EmployeeRepository;
import com.employeeinfo.data.Address;
import com.employeeinfo.data.Employee;
import com.employeeinfo.exception.InvalidEmployeeException;

@Service
@Transactional
public class EmployeeService {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private EmployeeRepository employeeRepository;

	@Autowired
	private AddressRepository addressRepository;

	@Transactional (timeout = 10, rollbackFor = InvalidEmployeeException.class)
	public String addNewEmployee(EmployeeForm employeeForm) throws InvalidEmployeeException {
		Employee e = new Employee();
		e.setName(employeeForm.getName());
		e.setDeptartment(employeeForm.getDeptartment());
		e.setDesignation(employeeForm.getDesignation());
		e.setSalary(employeeForm.getSalary());

		employeeRepository.save(e);
		
		Address a = new Address();
		a.setCity(employeeForm.getCity());
		a.setState(employeeForm.getState());
		a.setStreet(employeeForm.getStreet());
		a.setZipcode(employeeForm.getZipcode());
		addressRepository.save(a);
//
//		if(true)
//			throw new InvalidEmployeeException();
		
		return "Saved";
	}
	
	public Iterable<Employee> getAllEmployees() {
		return employeeRepository.findAll();
	}
	
}
